name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      with:
        root_file: thesis.tex

    - name: Compile LaTeX document (2nd time)
      uses: dante-ev/latex-action@master
      with:
        root_file: thesis.tex

    - name: Get short SHA
      id: vars
      run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

    - name: Create PDF file with SHA in its name
      run: mv thesis.pdf thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: thesis-lauinger-${{ steps.vars.outputs.sha_short }}
        path: thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: thesis.log

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Install pdftotext
        run: pip install pdftotext

      - name: Get short SHA
        id: vars
        run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

      - uses: actions/download-artifact@v2
        with:
          name: thesis-lauinger-${{ steps.vars.outputs.sha_short }}
          path: thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf

      - name: Report word count
        run: |
          pdftotext thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf
          wc -w thesis-lauinger-${{ steps.vars.outputs.sha_short }}.txt
