name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      with:
        root_file: thesis.tex

    - name: get shortsha
      id: vars
      run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

    - name: create PDF file with SHA in its name
      run: mv thesis.pdf thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: thesis-lauinger-${{ steps.vars.outputs.sha_short }}
        path: thesis-lauinger-${{ steps.vars.outputs.sha_short }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: thesis.log