name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      with:
        root_file: thesis.tex

    - name: Get file name
      id: vars
      run: echo ::set-output name=filename::thesis-lauinger-$(date +%Y%m%d)-(git rev-parse --short=7 ${{ github.sha }})

    - name: Create PDF file with SHA in its name
      run: mv thesis.pdf ${{ steps.vars.outputs.filename }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.vars.outputs.filename }}
        path: ${{ steps.vars.outputs.filename }}.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: thesis.log

  check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install pdftotext
        run: sudo apt-get install -y xpdf

      - name: Get file name
        id: vars
        run: echo ::set-output name=filename::thesis-lauinger-$(date +%Y%m%d)-(git rev-parse --short=7 ${{ github.sha }})

      - uses: actions/download-artifact@v2
        with:
          name: ${{ steps.vars.outputs.filename }}

      - name: What is in the directory?
        run: ls -la

      - name: Report word count
        run: |
          pdftotext ${{ steps.vars.outputs.filename }}.pdf
          wc -w ${{ steps.vars.outputs.filename }}.txt
