---
- name: "Configure vm6.rbg.informatik.tu-darmstadt.de"
  hosts: vm6
  user: root
  vars_files:
    - vaults/vm6_vault.yml
  roles:
    - base
    - ssh
    - unattended-upgrades
    - golang
    - jupyter
    - acquisition
    - nginx