---
- name: "Install SSH packages and Dependencies"
  apt: name={{ item }} state=present
  with_items:
    - openssh-server
  tags: ssh

- name: "Configure sshd"
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd
  tags: ssh

- name: "Ensure .ssh directory exists"
  file:
    dest: "{{ item }}/.ssh"
    state: directory
  with_items:
    - /root
  tags: ssh

- name: "Set up SSH keys"
  template:
    src: templates/authorized_keys.j2
    dest: "{{ item }}/.ssh/authorized_keys"
  with_items:
    - /root
  tags: ssh

