---
- name: "install nginx"
  package:
    name: nginx
  tags: nginx

- name: "deploy htpasswd file"
  template:
    src: notebook-users.htpasswd
    dest: /root/notebook-users.htpasswd
  tags: nginx

- name: "set up nginx configuation"
  template:
    src: vm6.conf
    dest: /etc/nginx/sites-enabled/vm6.conf
  tags: nginx

- name: "start and enable nginx"
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx